import React, { useState, useEffect, FormEvent } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { LiveSession } from '../types';
import GlassCard from './GlassCard';
import Button from './Button';
import TimezoneSelect from './TimezoneSelect';

interface SessionModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (session: LiveSession) => void;
  session: LiveSession | null;
}

const SessionModal: React.FC<SessionModalProps> = ({ isOpen, onClose, onSave, session }) => {
  const [title, setTitle] = useState('');
  const [date, setDate] = useState(''); // YYYY-MM-DD
  const [startTime, setStartTime] = useState(''); // HH:MM
  const [endTime, setEndTime] = useState(''); // HH:MM
  const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [capacity, setCapacity] = useState(30);

  useEffect(() => {
    if (isOpen) {
        if (session) {
            setTitle(session.title);
            const start = session.startTime;
            setDate(start.toISOString().split('T')[0]);
            setStartTime(start.toTimeString().substring(0, 5));
            setEndTime(session.endTime.toTimeString().substring(0, 5));
            setTimezone(session.timezone);
            setCapacity(session.capacity);
        } else {
            // Reset form for a new session
            setTitle('');
            setDate('');
            setStartTime('');
            setEndTime('');
            setTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone);
            setCapacity(30);
        }
    }
  }, [session, isOpen]);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    // In a real app, you would use a library like date-fns-tz for robust timezone handling.
    // For this demo, we create date objects from local time strings.
    const startDateTime = new Date(`${date}T${startTime}`);
    const endDateTime = new Date(`${date}T${endTime}`);

    onSave({
      id: session?.id || '', // ID will be generated by the parent
      title,
      startTime: startDateTime,
      endTime: endDateTime,
      timezone,
      capacity: Number(capacity),
      bookedStudents: session?.bookedStudents || [],
    });
    onClose();
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
            className="w-full max-w-lg"
            onClick={(e) => e.stopPropagation()}
          >
            <GlassCard className="p-8">
              <h2 className="text-2xl font-bold mb-6">{session ? 'Edit Session' : 'Create New Session'}</h2>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label htmlFor="title" className="block text-sm font-medium text-gray-300">Session Title</label>
                  <input type="text" id="title" value={title} onChange={(e) => setTitle(e.target.value)} required className="mt-1 block w-full bg-white/5 border border-white/10 rounded-md py-2 px-3 text-sm focus:ring-2 focus:ring-nebula-600 focus:outline-none" />
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="sm:col-span-1">
                        <label htmlFor="date" className="block text-sm font-medium text-gray-300">Date</label>
                        <input type="date" id="date" value={date} onChange={(e) => setDate(e.target.value)} required className="mt-1 block w-full bg-white/5 border border-white/10 rounded-md py-2 px-3 text-sm focus:ring-2 focus:ring-nebula-600 focus:outline-none" />
                    </div>
                     <div className="sm:col-span-1">
                        <label htmlFor="startTime" className="block text-sm font-medium text-gray-300">Start Time</label>
                        <input type="time" id="startTime" value={startTime} onChange={(e) => setStartTime(e.target.value)} required className="mt-1 block w-full bg-white/5 border border-white/10 rounded-md py-2 px-3 text-sm focus:ring-2 focus:ring-nebula-600 focus:outline-none" />
                    </div>
                    <div className="sm:col-span-1">
                        <label htmlFor="endTime" className="block text-sm font-medium text-gray-300">End Time</label>
                        <input type="time" id="endTime" value={endTime} onChange={(e) => setEndTime(e.target.value)} required className="mt-1 block w-full bg-white/5 border border-white/10 rounded-md py-2 px-3 text-sm focus:ring-2 focus:ring-nebula-600 focus:outline-none" />
                    </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                         <label htmlFor="timezone" className="block text-sm font-medium text-gray-300">Timezone</label>
                         <TimezoneSelect value={timezone} onChange={setTimezone} />
                    </div>
                    <div>
                        <label htmlFor="capacity" className="block text-sm font-medium text-gray-300">Capacity</label>
                        <input type="number" id="capacity" value={capacity} onChange={(e) => setCapacity(parseInt(e.target.value))} min="1" required className="mt-1 block w-full bg-white/5 border border-white/10 rounded-md py-2 px-3 text-sm focus:ring-2 focus:ring-nebula-600 focus:outline-none" />
                    </div>
                </div>

                <div className="flex justify-end space-x-4 pt-4">
                  <Button variant="secondary" onClick={onClose} type="button">Cancel</Button>
                  <Button variant="primary" type="submit">Save Session</Button>
                </div>
              </form>
            </GlassCard>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default SessionModal;